sudo: required
dist: trusty
language: scala
scala:
 - 2.11.8
env:
 - export LD_LIBRARY_PATH=/usr/local/lib
script:
 - mvn install
jdk:
 - oraclejdk8
after_success:
    - COMMIT=$(echo $TRAVIS_COMMIT | head -c 7)
    - tar -cjf eclair_$COMMIT.tar.bz2 -C /home/travis/build/ACINQ/eclair/ .
    - if [ -f eclair_$COMMIT.tar.bz2 ]; then travis_retry curl --max-time 60 --upload eclair_$COMMIT.tar.bz2 https://transfer.sh/eclair_$COMMIT.tar.bz2; fi
